//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scrips/PlayerController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerController : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerController"",
    ""maps"": [
        {
            ""name"": ""GamePad"",
            ""id"": ""8c581f61-ed4d-4c78-87d7-12cb123b7f0c"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""642f1fda-ca68-4964-b112-6221fdc95260"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""8de82f64-5122-4be2-8b9a-1cf4fbd60da9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""2d46fb30-47c5-42f5-8182-7aa2b2690bfd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Kick"",
                    ""type"": ""Button"",
                    ""id"": ""1cabb8bb-fce7-4013-b8bd-c4adac9b80e6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Block"",
                    ""type"": ""Button"",
                    ""id"": ""1c9e94ac-11f9-443f-82ac-6534f3778ab6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""e3637b5e-f1ef-4424-a194-b5e406d9d5f4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""da91bd5d-0650-4dcf-b4a8-96eed50b53de"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1c7ef3a-e33d-4dee-8863-c6d067e9c72e"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""026ca0d0-4a0d-4477-ae7a-d1d6caed1b3b"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""db1eedd4-77c9-49fe-ab0c-1211d740e411"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Kick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e15243a8-a988-4b94-8a3c-45590ab5219a"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""26e075db-d4c2-47e1-9420-8d2cf908df7a"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""KeyBoard"",
            ""id"": ""8002c6ca-492c-4633-afa5-75c9418b593f"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""325ced5e-32bb-4e1c-b1d4-3b773d16eef9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""92a7b629-66ca-428d-b22b-53a11afe1330"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""15d52f12-8d98-4254-878a-9f30d3b8aa82"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Kick"",
                    ""type"": ""Button"",
                    ""id"": ""85cf3d2b-b42d-41fb-bec4-6ba5f6e88358"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Block"",
                    ""type"": ""Button"",
                    ""id"": ""ffbd9bf6-9a8f-4470-8d11-f54746988ddd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""1e643957-9952-497a-94fc-e00d31fecc31"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""94ccf701-ad11-4e18-badb-5abcd289f449"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7bc82184-9e52-413b-96bd-dc1c5b4d1146"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c9ebfeb2-2e4c-4bf1-a383-51d2c8d575b1"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""765480c0-fa25-4c46-879e-aaf3e8e82ef8"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""0e273014-be01-48dc-9a56-1a60a545bd94"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""af961d86-8c7b-4e31-b9b3-b9807e900dca"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e8e10e8c-3c2a-488b-bbfb-5d1eadae4c89"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f472cd52-eb25-48f3-af12-3cf4799500fd"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Kick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1b0a714-4c22-4c8b-b012-591a4bbb2275"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da0d4beb-5d06-4319-8084-8ec5d54a7699"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""JoyStick"",
            ""id"": ""1d6f682a-e3d2-4671-a3d0-0d98eceb7d8f"",
            ""actions"": [
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""d3037a77-9737-40d1-85e9-4c69c25abe94"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""bbbd0366-9b15-4179-a801-46c89525652f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""d390f37a-6386-48f9-9652-e89ebfd11f5f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Kick"",
                    ""type"": ""Button"",
                    ""id"": ""8fafb0fd-016b-41c6-b499-892702378a79"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Block"",
                    ""type"": ""Button"",
                    ""id"": ""bf78acf9-dc73-45d2-8105-9c75516d8eb9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""6fbeae02-ba25-42c1-b7d5-69eadebfd55e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""fb012202-168c-48ee-b797-6a6cf9424f18"",
                    ""path"": ""<HID::PC Game Controller       >/button4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""124a0b1f-ee30-43e8-9fab-42e2d1333120"",
                    ""path"": ""<HID::PC Game Controller       >/button3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e80878d9-6b1c-43e2-8e9d-f1b39e1f5b94"",
                    ""path"": ""<Joystick>/stick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PcGamePad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""661dde19-ae37-417f-be84-2be90bc5f79c"",
                    ""path"": ""<HID::PC Game Controller       >/button2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Kick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""673771f7-f928-446a-9634-b830916f9418"",
                    ""path"": ""<HID::PC Game Controller       >/button5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9941be5c-246d-49c9-9994-7a1f2c5e197f"",
                    ""path"": ""<HID::PC Game Controller       >/button12"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""KeyBoardShared"",
            ""id"": ""134b8cf7-d957-42dc-97a9-bf6389a1bf9e"",
            ""actions"": [
                {
                    ""name"": ""P1Move"",
                    ""type"": ""Value"",
                    ""id"": ""46b9600e-0f52-4682-a6c9-eefbe21671ee"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""P1Attack"",
                    ""type"": ""Button"",
                    ""id"": ""a1718547-c0cd-4e3a-86dc-fa9bca40d741"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P1Jump"",
                    ""type"": ""Button"",
                    ""id"": ""522e8a08-63b6-49bb-b219-6ba6f41cdc8d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P1Kick"",
                    ""type"": ""Button"",
                    ""id"": ""546ea3d7-ea16-40aa-b625-b3352782e6fa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P1Block"",
                    ""type"": ""Button"",
                    ""id"": ""70f5131d-0df0-4310-a649-798e564dfcac"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P1Back"",
                    ""type"": ""Button"",
                    ""id"": ""9b267a69-167d-440b-99f9-e1e731071476"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P2Move1"",
                    ""type"": ""Value"",
                    ""id"": ""0f8df058-89b7-424c-957c-9c9195e9877b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""P2Attack1"",
                    ""type"": ""Button"",
                    ""id"": ""537b7a45-7688-41c6-815a-0f59b921d91e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P2Jump1"",
                    ""type"": ""Button"",
                    ""id"": ""eb0e7e8e-72e0-415e-b28f-7968639092aa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P2Kick1"",
                    ""type"": ""Button"",
                    ""id"": ""133b496b-d874-4c2e-aaf4-4edde980d92a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P2Block1"",
                    ""type"": ""Button"",
                    ""id"": ""29f11566-7a64-4bd3-b761-5e340e6a1fd5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P2Back1"",
                    ""type"": ""Button"",
                    ""id"": ""9b6ee044-f618-4a17-a48e-df7cae927e8d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""14327a2f-e030-48c6-8725-9cd8bc847a6b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7bf3fa36-184d-4777-8ce2-80b80936c511"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1fd973cf-926d-4faa-86f8-a51256f53dfb"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""ed117eee-4112-45da-83db-f11dccfbd489"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4f56e482-b9a8-4094-8d4c-26dff83b2864"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c521c45e-2457-4b8e-b467-131424e39f0b"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ecd4e664-6c59-41c2-b845-cbc0f2fe0254"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd014520-d035-4eb8-823c-ce962d7213c6"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Kick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7ada283b-7339-44d6-a264-2be334dc7d86"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""13ff29d7-8169-4e76-aacd-7a681f881230"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""9675e0fb-6e25-4412-8f5a-fde920e6659e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2Move1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e52e825a-646a-4b0c-87f5-ca7ff0310731"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2Move1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e6163ed8-6a39-481d-bce7-68eac9cb5df5"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2Move1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""36efa9b6-6d8f-43f5-bfdc-990428f9860e"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2Move1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""eda0bbad-3657-4c49-a322-683218383f10"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2Move1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""51ff15d0-454b-468b-9ddd-9ad8b8eb67dc"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2Attack1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a9648299-4c1f-42da-8b19-413eb9c0d03b"",
                    ""path"": ""<Keyboard>/numpad0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2Jump1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0809714f-c04c-4e51-bff0-8c175d40c409"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2Kick1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""33fbc0d3-90a3-4602-96cd-c8d417242d79"",
                    ""path"": ""<Keyboard>/numpad5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2Block1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e1f5763-64b3-42d9-ab86-91dd89b07819"",
                    ""path"": ""<Keyboard>/numpad9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2Back1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""KeyBoard"",
            ""bindingGroup"": ""KeyBoard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""GamePad"",
            ""bindingGroup"": ""GamePad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""PcGamePad"",
            ""bindingGroup"": ""PcGamePad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Joystick>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // GamePad
        m_GamePad = asset.FindActionMap("GamePad", throwIfNotFound: true);
        m_GamePad_Move = m_GamePad.FindAction("Move", throwIfNotFound: true);
        m_GamePad_Jump = m_GamePad.FindAction("Jump", throwIfNotFound: true);
        m_GamePad_Attack = m_GamePad.FindAction("Attack", throwIfNotFound: true);
        m_GamePad_Kick = m_GamePad.FindAction("Kick", throwIfNotFound: true);
        m_GamePad_Block = m_GamePad.FindAction("Block", throwIfNotFound: true);
        m_GamePad_Back = m_GamePad.FindAction("Back", throwIfNotFound: true);
        // KeyBoard
        m_KeyBoard = asset.FindActionMap("KeyBoard", throwIfNotFound: true);
        m_KeyBoard_Move = m_KeyBoard.FindAction("Move", throwIfNotFound: true);
        m_KeyBoard_Attack = m_KeyBoard.FindAction("Attack", throwIfNotFound: true);
        m_KeyBoard_Jump = m_KeyBoard.FindAction("Jump", throwIfNotFound: true);
        m_KeyBoard_Kick = m_KeyBoard.FindAction("Kick", throwIfNotFound: true);
        m_KeyBoard_Block = m_KeyBoard.FindAction("Block", throwIfNotFound: true);
        m_KeyBoard_Back = m_KeyBoard.FindAction("Back", throwIfNotFound: true);
        // JoyStick
        m_JoyStick = asset.FindActionMap("JoyStick", throwIfNotFound: true);
        m_JoyStick_Attack = m_JoyStick.FindAction("Attack", throwIfNotFound: true);
        m_JoyStick_Move = m_JoyStick.FindAction("Move", throwIfNotFound: true);
        m_JoyStick_Jump = m_JoyStick.FindAction("Jump", throwIfNotFound: true);
        m_JoyStick_Kick = m_JoyStick.FindAction("Kick", throwIfNotFound: true);
        m_JoyStick_Block = m_JoyStick.FindAction("Block", throwIfNotFound: true);
        m_JoyStick_Back = m_JoyStick.FindAction("Back", throwIfNotFound: true);
        // KeyBoardShared
        m_KeyBoardShared = asset.FindActionMap("KeyBoardShared", throwIfNotFound: true);
        m_KeyBoardShared_P1Move = m_KeyBoardShared.FindAction("P1Move", throwIfNotFound: true);
        m_KeyBoardShared_P1Attack = m_KeyBoardShared.FindAction("P1Attack", throwIfNotFound: true);
        m_KeyBoardShared_P1Jump = m_KeyBoardShared.FindAction("P1Jump", throwIfNotFound: true);
        m_KeyBoardShared_P1Kick = m_KeyBoardShared.FindAction("P1Kick", throwIfNotFound: true);
        m_KeyBoardShared_P1Block = m_KeyBoardShared.FindAction("P1Block", throwIfNotFound: true);
        m_KeyBoardShared_P1Back = m_KeyBoardShared.FindAction("P1Back", throwIfNotFound: true);
        m_KeyBoardShared_P2Move1 = m_KeyBoardShared.FindAction("P2Move1", throwIfNotFound: true);
        m_KeyBoardShared_P2Attack1 = m_KeyBoardShared.FindAction("P2Attack1", throwIfNotFound: true);
        m_KeyBoardShared_P2Jump1 = m_KeyBoardShared.FindAction("P2Jump1", throwIfNotFound: true);
        m_KeyBoardShared_P2Kick1 = m_KeyBoardShared.FindAction("P2Kick1", throwIfNotFound: true);
        m_KeyBoardShared_P2Block1 = m_KeyBoardShared.FindAction("P2Block1", throwIfNotFound: true);
        m_KeyBoardShared_P2Back1 = m_KeyBoardShared.FindAction("P2Back1", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GamePad
    private readonly InputActionMap m_GamePad;
    private IGamePadActions m_GamePadActionsCallbackInterface;
    private readonly InputAction m_GamePad_Move;
    private readonly InputAction m_GamePad_Jump;
    private readonly InputAction m_GamePad_Attack;
    private readonly InputAction m_GamePad_Kick;
    private readonly InputAction m_GamePad_Block;
    private readonly InputAction m_GamePad_Back;
    public struct GamePadActions
    {
        private @PlayerController m_Wrapper;
        public GamePadActions(@PlayerController wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_GamePad_Move;
        public InputAction @Jump => m_Wrapper.m_GamePad_Jump;
        public InputAction @Attack => m_Wrapper.m_GamePad_Attack;
        public InputAction @Kick => m_Wrapper.m_GamePad_Kick;
        public InputAction @Block => m_Wrapper.m_GamePad_Block;
        public InputAction @Back => m_Wrapper.m_GamePad_Back;
        public InputActionMap Get() { return m_Wrapper.m_GamePad; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GamePadActions set) { return set.Get(); }
        public void SetCallbacks(IGamePadActions instance)
        {
            if (m_Wrapper.m_GamePadActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_GamePadActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_GamePadActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_GamePadActionsCallbackInterface.OnMove;
                @Jump.started -= m_Wrapper.m_GamePadActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_GamePadActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_GamePadActionsCallbackInterface.OnJump;
                @Attack.started -= m_Wrapper.m_GamePadActionsCallbackInterface.OnAttack;
                @Attack.performed -= m_Wrapper.m_GamePadActionsCallbackInterface.OnAttack;
                @Attack.canceled -= m_Wrapper.m_GamePadActionsCallbackInterface.OnAttack;
                @Kick.started -= m_Wrapper.m_GamePadActionsCallbackInterface.OnKick;
                @Kick.performed -= m_Wrapper.m_GamePadActionsCallbackInterface.OnKick;
                @Kick.canceled -= m_Wrapper.m_GamePadActionsCallbackInterface.OnKick;
                @Block.started -= m_Wrapper.m_GamePadActionsCallbackInterface.OnBlock;
                @Block.performed -= m_Wrapper.m_GamePadActionsCallbackInterface.OnBlock;
                @Block.canceled -= m_Wrapper.m_GamePadActionsCallbackInterface.OnBlock;
                @Back.started -= m_Wrapper.m_GamePadActionsCallbackInterface.OnBack;
                @Back.performed -= m_Wrapper.m_GamePadActionsCallbackInterface.OnBack;
                @Back.canceled -= m_Wrapper.m_GamePadActionsCallbackInterface.OnBack;
            }
            m_Wrapper.m_GamePadActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Attack.started += instance.OnAttack;
                @Attack.performed += instance.OnAttack;
                @Attack.canceled += instance.OnAttack;
                @Kick.started += instance.OnKick;
                @Kick.performed += instance.OnKick;
                @Kick.canceled += instance.OnKick;
                @Block.started += instance.OnBlock;
                @Block.performed += instance.OnBlock;
                @Block.canceled += instance.OnBlock;
                @Back.started += instance.OnBack;
                @Back.performed += instance.OnBack;
                @Back.canceled += instance.OnBack;
            }
        }
    }
    public GamePadActions @GamePad => new GamePadActions(this);

    // KeyBoard
    private readonly InputActionMap m_KeyBoard;
    private IKeyBoardActions m_KeyBoardActionsCallbackInterface;
    private readonly InputAction m_KeyBoard_Move;
    private readonly InputAction m_KeyBoard_Attack;
    private readonly InputAction m_KeyBoard_Jump;
    private readonly InputAction m_KeyBoard_Kick;
    private readonly InputAction m_KeyBoard_Block;
    private readonly InputAction m_KeyBoard_Back;
    public struct KeyBoardActions
    {
        private @PlayerController m_Wrapper;
        public KeyBoardActions(@PlayerController wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_KeyBoard_Move;
        public InputAction @Attack => m_Wrapper.m_KeyBoard_Attack;
        public InputAction @Jump => m_Wrapper.m_KeyBoard_Jump;
        public InputAction @Kick => m_Wrapper.m_KeyBoard_Kick;
        public InputAction @Block => m_Wrapper.m_KeyBoard_Block;
        public InputAction @Back => m_Wrapper.m_KeyBoard_Back;
        public InputActionMap Get() { return m_Wrapper.m_KeyBoard; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(KeyBoardActions set) { return set.Get(); }
        public void SetCallbacks(IKeyBoardActions instance)
        {
            if (m_Wrapper.m_KeyBoardActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_KeyBoardActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_KeyBoardActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_KeyBoardActionsCallbackInterface.OnMove;
                @Attack.started -= m_Wrapper.m_KeyBoardActionsCallbackInterface.OnAttack;
                @Attack.performed -= m_Wrapper.m_KeyBoardActionsCallbackInterface.OnAttack;
                @Attack.canceled -= m_Wrapper.m_KeyBoardActionsCallbackInterface.OnAttack;
                @Jump.started -= m_Wrapper.m_KeyBoardActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_KeyBoardActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_KeyBoardActionsCallbackInterface.OnJump;
                @Kick.started -= m_Wrapper.m_KeyBoardActionsCallbackInterface.OnKick;
                @Kick.performed -= m_Wrapper.m_KeyBoardActionsCallbackInterface.OnKick;
                @Kick.canceled -= m_Wrapper.m_KeyBoardActionsCallbackInterface.OnKick;
                @Block.started -= m_Wrapper.m_KeyBoardActionsCallbackInterface.OnBlock;
                @Block.performed -= m_Wrapper.m_KeyBoardActionsCallbackInterface.OnBlock;
                @Block.canceled -= m_Wrapper.m_KeyBoardActionsCallbackInterface.OnBlock;
                @Back.started -= m_Wrapper.m_KeyBoardActionsCallbackInterface.OnBack;
                @Back.performed -= m_Wrapper.m_KeyBoardActionsCallbackInterface.OnBack;
                @Back.canceled -= m_Wrapper.m_KeyBoardActionsCallbackInterface.OnBack;
            }
            m_Wrapper.m_KeyBoardActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Attack.started += instance.OnAttack;
                @Attack.performed += instance.OnAttack;
                @Attack.canceled += instance.OnAttack;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Kick.started += instance.OnKick;
                @Kick.performed += instance.OnKick;
                @Kick.canceled += instance.OnKick;
                @Block.started += instance.OnBlock;
                @Block.performed += instance.OnBlock;
                @Block.canceled += instance.OnBlock;
                @Back.started += instance.OnBack;
                @Back.performed += instance.OnBack;
                @Back.canceled += instance.OnBack;
            }
        }
    }
    public KeyBoardActions @KeyBoard => new KeyBoardActions(this);

    // JoyStick
    private readonly InputActionMap m_JoyStick;
    private IJoyStickActions m_JoyStickActionsCallbackInterface;
    private readonly InputAction m_JoyStick_Attack;
    private readonly InputAction m_JoyStick_Move;
    private readonly InputAction m_JoyStick_Jump;
    private readonly InputAction m_JoyStick_Kick;
    private readonly InputAction m_JoyStick_Block;
    private readonly InputAction m_JoyStick_Back;
    public struct JoyStickActions
    {
        private @PlayerController m_Wrapper;
        public JoyStickActions(@PlayerController wrapper) { m_Wrapper = wrapper; }
        public InputAction @Attack => m_Wrapper.m_JoyStick_Attack;
        public InputAction @Move => m_Wrapper.m_JoyStick_Move;
        public InputAction @Jump => m_Wrapper.m_JoyStick_Jump;
        public InputAction @Kick => m_Wrapper.m_JoyStick_Kick;
        public InputAction @Block => m_Wrapper.m_JoyStick_Block;
        public InputAction @Back => m_Wrapper.m_JoyStick_Back;
        public InputActionMap Get() { return m_Wrapper.m_JoyStick; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(JoyStickActions set) { return set.Get(); }
        public void SetCallbacks(IJoyStickActions instance)
        {
            if (m_Wrapper.m_JoyStickActionsCallbackInterface != null)
            {
                @Attack.started -= m_Wrapper.m_JoyStickActionsCallbackInterface.OnAttack;
                @Attack.performed -= m_Wrapper.m_JoyStickActionsCallbackInterface.OnAttack;
                @Attack.canceled -= m_Wrapper.m_JoyStickActionsCallbackInterface.OnAttack;
                @Move.started -= m_Wrapper.m_JoyStickActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_JoyStickActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_JoyStickActionsCallbackInterface.OnMove;
                @Jump.started -= m_Wrapper.m_JoyStickActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_JoyStickActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_JoyStickActionsCallbackInterface.OnJump;
                @Kick.started -= m_Wrapper.m_JoyStickActionsCallbackInterface.OnKick;
                @Kick.performed -= m_Wrapper.m_JoyStickActionsCallbackInterface.OnKick;
                @Kick.canceled -= m_Wrapper.m_JoyStickActionsCallbackInterface.OnKick;
                @Block.started -= m_Wrapper.m_JoyStickActionsCallbackInterface.OnBlock;
                @Block.performed -= m_Wrapper.m_JoyStickActionsCallbackInterface.OnBlock;
                @Block.canceled -= m_Wrapper.m_JoyStickActionsCallbackInterface.OnBlock;
                @Back.started -= m_Wrapper.m_JoyStickActionsCallbackInterface.OnBack;
                @Back.performed -= m_Wrapper.m_JoyStickActionsCallbackInterface.OnBack;
                @Back.canceled -= m_Wrapper.m_JoyStickActionsCallbackInterface.OnBack;
            }
            m_Wrapper.m_JoyStickActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Attack.started += instance.OnAttack;
                @Attack.performed += instance.OnAttack;
                @Attack.canceled += instance.OnAttack;
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Kick.started += instance.OnKick;
                @Kick.performed += instance.OnKick;
                @Kick.canceled += instance.OnKick;
                @Block.started += instance.OnBlock;
                @Block.performed += instance.OnBlock;
                @Block.canceled += instance.OnBlock;
                @Back.started += instance.OnBack;
                @Back.performed += instance.OnBack;
                @Back.canceled += instance.OnBack;
            }
        }
    }
    public JoyStickActions @JoyStick => new JoyStickActions(this);

    // KeyBoardShared
    private readonly InputActionMap m_KeyBoardShared;
    private IKeyBoardSharedActions m_KeyBoardSharedActionsCallbackInterface;
    private readonly InputAction m_KeyBoardShared_P1Move;
    private readonly InputAction m_KeyBoardShared_P1Attack;
    private readonly InputAction m_KeyBoardShared_P1Jump;
    private readonly InputAction m_KeyBoardShared_P1Kick;
    private readonly InputAction m_KeyBoardShared_P1Block;
    private readonly InputAction m_KeyBoardShared_P1Back;
    private readonly InputAction m_KeyBoardShared_P2Move1;
    private readonly InputAction m_KeyBoardShared_P2Attack1;
    private readonly InputAction m_KeyBoardShared_P2Jump1;
    private readonly InputAction m_KeyBoardShared_P2Kick1;
    private readonly InputAction m_KeyBoardShared_P2Block1;
    private readonly InputAction m_KeyBoardShared_P2Back1;
    public struct KeyBoardSharedActions
    {
        private @PlayerController m_Wrapper;
        public KeyBoardSharedActions(@PlayerController wrapper) { m_Wrapper = wrapper; }
        public InputAction @P1Move => m_Wrapper.m_KeyBoardShared_P1Move;
        public InputAction @P1Attack => m_Wrapper.m_KeyBoardShared_P1Attack;
        public InputAction @P1Jump => m_Wrapper.m_KeyBoardShared_P1Jump;
        public InputAction @P1Kick => m_Wrapper.m_KeyBoardShared_P1Kick;
        public InputAction @P1Block => m_Wrapper.m_KeyBoardShared_P1Block;
        public InputAction @P1Back => m_Wrapper.m_KeyBoardShared_P1Back;
        public InputAction @P2Move1 => m_Wrapper.m_KeyBoardShared_P2Move1;
        public InputAction @P2Attack1 => m_Wrapper.m_KeyBoardShared_P2Attack1;
        public InputAction @P2Jump1 => m_Wrapper.m_KeyBoardShared_P2Jump1;
        public InputAction @P2Kick1 => m_Wrapper.m_KeyBoardShared_P2Kick1;
        public InputAction @P2Block1 => m_Wrapper.m_KeyBoardShared_P2Block1;
        public InputAction @P2Back1 => m_Wrapper.m_KeyBoardShared_P2Back1;
        public InputActionMap Get() { return m_Wrapper.m_KeyBoardShared; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(KeyBoardSharedActions set) { return set.Get(); }
        public void SetCallbacks(IKeyBoardSharedActions instance)
        {
            if (m_Wrapper.m_KeyBoardSharedActionsCallbackInterface != null)
            {
                @P1Move.started -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP1Move;
                @P1Move.performed -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP1Move;
                @P1Move.canceled -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP1Move;
                @P1Attack.started -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP1Attack;
                @P1Attack.performed -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP1Attack;
                @P1Attack.canceled -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP1Attack;
                @P1Jump.started -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP1Jump;
                @P1Jump.performed -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP1Jump;
                @P1Jump.canceled -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP1Jump;
                @P1Kick.started -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP1Kick;
                @P1Kick.performed -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP1Kick;
                @P1Kick.canceled -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP1Kick;
                @P1Block.started -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP1Block;
                @P1Block.performed -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP1Block;
                @P1Block.canceled -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP1Block;
                @P1Back.started -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP1Back;
                @P1Back.performed -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP1Back;
                @P1Back.canceled -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP1Back;
                @P2Move1.started -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP2Move1;
                @P2Move1.performed -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP2Move1;
                @P2Move1.canceled -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP2Move1;
                @P2Attack1.started -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP2Attack1;
                @P2Attack1.performed -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP2Attack1;
                @P2Attack1.canceled -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP2Attack1;
                @P2Jump1.started -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP2Jump1;
                @P2Jump1.performed -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP2Jump1;
                @P2Jump1.canceled -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP2Jump1;
                @P2Kick1.started -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP2Kick1;
                @P2Kick1.performed -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP2Kick1;
                @P2Kick1.canceled -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP2Kick1;
                @P2Block1.started -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP2Block1;
                @P2Block1.performed -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP2Block1;
                @P2Block1.canceled -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP2Block1;
                @P2Back1.started -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP2Back1;
                @P2Back1.performed -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP2Back1;
                @P2Back1.canceled -= m_Wrapper.m_KeyBoardSharedActionsCallbackInterface.OnP2Back1;
            }
            m_Wrapper.m_KeyBoardSharedActionsCallbackInterface = instance;
            if (instance != null)
            {
                @P1Move.started += instance.OnP1Move;
                @P1Move.performed += instance.OnP1Move;
                @P1Move.canceled += instance.OnP1Move;
                @P1Attack.started += instance.OnP1Attack;
                @P1Attack.performed += instance.OnP1Attack;
                @P1Attack.canceled += instance.OnP1Attack;
                @P1Jump.started += instance.OnP1Jump;
                @P1Jump.performed += instance.OnP1Jump;
                @P1Jump.canceled += instance.OnP1Jump;
                @P1Kick.started += instance.OnP1Kick;
                @P1Kick.performed += instance.OnP1Kick;
                @P1Kick.canceled += instance.OnP1Kick;
                @P1Block.started += instance.OnP1Block;
                @P1Block.performed += instance.OnP1Block;
                @P1Block.canceled += instance.OnP1Block;
                @P1Back.started += instance.OnP1Back;
                @P1Back.performed += instance.OnP1Back;
                @P1Back.canceled += instance.OnP1Back;
                @P2Move1.started += instance.OnP2Move1;
                @P2Move1.performed += instance.OnP2Move1;
                @P2Move1.canceled += instance.OnP2Move1;
                @P2Attack1.started += instance.OnP2Attack1;
                @P2Attack1.performed += instance.OnP2Attack1;
                @P2Attack1.canceled += instance.OnP2Attack1;
                @P2Jump1.started += instance.OnP2Jump1;
                @P2Jump1.performed += instance.OnP2Jump1;
                @P2Jump1.canceled += instance.OnP2Jump1;
                @P2Kick1.started += instance.OnP2Kick1;
                @P2Kick1.performed += instance.OnP2Kick1;
                @P2Kick1.canceled += instance.OnP2Kick1;
                @P2Block1.started += instance.OnP2Block1;
                @P2Block1.performed += instance.OnP2Block1;
                @P2Block1.canceled += instance.OnP2Block1;
                @P2Back1.started += instance.OnP2Back1;
                @P2Back1.performed += instance.OnP2Back1;
                @P2Back1.canceled += instance.OnP2Back1;
            }
        }
    }
    public KeyBoardSharedActions @KeyBoardShared => new KeyBoardSharedActions(this);
    private int m_KeyBoardSchemeIndex = -1;
    public InputControlScheme KeyBoardScheme
    {
        get
        {
            if (m_KeyBoardSchemeIndex == -1) m_KeyBoardSchemeIndex = asset.FindControlSchemeIndex("KeyBoard");
            return asset.controlSchemes[m_KeyBoardSchemeIndex];
        }
    }
    private int m_GamePadSchemeIndex = -1;
    public InputControlScheme GamePadScheme
    {
        get
        {
            if (m_GamePadSchemeIndex == -1) m_GamePadSchemeIndex = asset.FindControlSchemeIndex("GamePad");
            return asset.controlSchemes[m_GamePadSchemeIndex];
        }
    }
    private int m_PcGamePadSchemeIndex = -1;
    public InputControlScheme PcGamePadScheme
    {
        get
        {
            if (m_PcGamePadSchemeIndex == -1) m_PcGamePadSchemeIndex = asset.FindControlSchemeIndex("PcGamePad");
            return asset.controlSchemes[m_PcGamePadSchemeIndex];
        }
    }
    public interface IGamePadActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnKick(InputAction.CallbackContext context);
        void OnBlock(InputAction.CallbackContext context);
        void OnBack(InputAction.CallbackContext context);
    }
    public interface IKeyBoardActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnKick(InputAction.CallbackContext context);
        void OnBlock(InputAction.CallbackContext context);
        void OnBack(InputAction.CallbackContext context);
    }
    public interface IJoyStickActions
    {
        void OnAttack(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnKick(InputAction.CallbackContext context);
        void OnBlock(InputAction.CallbackContext context);
        void OnBack(InputAction.CallbackContext context);
    }
    public interface IKeyBoardSharedActions
    {
        void OnP1Move(InputAction.CallbackContext context);
        void OnP1Attack(InputAction.CallbackContext context);
        void OnP1Jump(InputAction.CallbackContext context);
        void OnP1Kick(InputAction.CallbackContext context);
        void OnP1Block(InputAction.CallbackContext context);
        void OnP1Back(InputAction.CallbackContext context);
        void OnP2Move1(InputAction.CallbackContext context);
        void OnP2Attack1(InputAction.CallbackContext context);
        void OnP2Jump1(InputAction.CallbackContext context);
        void OnP2Kick1(InputAction.CallbackContext context);
        void OnP2Block1(InputAction.CallbackContext context);
        void OnP2Back1(InputAction.CallbackContext context);
    }
}
